import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Strata Management",
  description: "Generated by Vercel, a cloud-platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        {children}
      </body>
    </html>
  );
}
